config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end

  resources :users, :posts
end

app/models/post.rb
class Post < ActiveRecord::Base

	# Friendly ID
  extend FriendlyId
  friendly_id :title, use: :slugged

	# Associations
  belongs_to :user

  # Validations
  validates :body, presence: true
  validates :title, presence: true


  
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :posts

  # Validations
  validates :name, :email, :password, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.order(created_at: :desc).page( params[:page] )
	end

	 def show
    @post = Post.friendly.find(params[:id])
  end

	def new
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new( post_params )
		authorize User
		if @post.save
  		flash[:notice] = "Post added successfully."
  		redirect_to root_path
  	else
  		flash[:error] = "There was a problem saving the post."
  		render action: :new
  	end
	end

	def edit
		@post = current_user.posts.friendly.find(params[:id])
	end

	def update
		@post = current_user.posts.friendly.find(params[:id])
    if @post.update_attributes( post_params )
      flash[:notice] = "Saved post updates."
      redirect_to root_path
    else
      flash[:error] = "The post could not be saved."
      render action: :edit
    end
	end

	def destroy
		 @post = current_user.post.friendly.find(params[:id])
    if @post.destroy
      flash[:notice] = "The post was deleted."
    else
      flash[:error] = "The post could not be deleted."
    end
    redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def create
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <%= link_to 'Home', root_path, class: 'blog-nav-item active' %>
      <%= render 'layouts/navigation_links' %>
    </nav>
  </div>
</div> 

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
	<%= link_to 'New Post', new_post_path, class: 'blog-nav-item' %>
	<%= link_to 'List Users', users_path, class: 'blog-nav-item' %>
	<%= link_to 'Sign Out', destroy_user_session_path, method: 'delete', class: 'blog-nav-item' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Personal Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Personal Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <!-- <main role="main"> -->
       <%= render 'layouts/messages' %>
       <div class="container">
        <div class="blog-header">
          <h1 class="blog-title">See What Develops...</h1>
          <p class="lead blog-description">The development blog that's focused on, structured around, and always in... development.</p>
        </div>
          <div class="row">
            <%= yield %>
          </div>
       </div>
    <!-- </main> -->
    <footer>
      <div class="blog-footer">
        <p><a href="#">See What Develops</a> is built with <a href="https:rubyonrails.org">Ruby on Rails</a> by <a href="https://twitter.com/davemoorestudio">@Dave Moore</a><br />
        Frontend framework by <a href="http://getbootstrap.com">Bootstrap</a><br /> 
        CSS tweaks based on customizations by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
          <a href="#">Back to top</a>
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-sm-12 blog-main">
	<div class="blog-post">
		<h2 class="blog-post-title">Create a New Post</h2>
		<%= simple_form_for @post do |f| %>
			<%= f.input :title, label: 'Post Title', input_html: { size: 85 } %>
        <br />
			  <%= f.input :body, label: 'Post Body', input_html: { class: 'tinymce', rows: 10, cols: 120 } %>
        <br />
			  <%= f.button :submit %>
    <% end %>
    <%= tinymce %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="col-sm-8 blog-main">
  <div class="blog-post">
    <% @posts.each do |post|%>
      <h2 class="blog-post-title"><%= post.title %></h2>
      <p class="blog-post-meta"><%= post.created_at.to_date.to_formatted_s :long_ordinal %> by Dave Moore</p>
      <hr>
      <%= raw post.body %>
      <p class="blog-post-meta"><%= link_to("Discuss This Post", post_path(post)) %></p>
    <% end %>
    <hr>
    <!-- kaminari pagination -->
    <div class="kaminari-newer"><%= link_to_previous_page @posts, 'Previous Post' %></div>
    <div class="kaminari-older"><%= link_to_next_page @posts, 'Next Post' %></div>
  </div>
</div>
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module sidebat-module-inset">
    <div class="circular"></div>
    <hr>
    

  </div>
</div>

app/views/posts/new.html.erb
<div class="col-sm-12 blog-main">
	<div class="blog-post">
		<h2 class="blog-post-title">Create a New Post</h2>
		<%= simple_form_for @post do |f| %>
			<%= f.input :title, label: 'Post Title', input_html: { size: 85 } %>
        <br />
			  <%= f.input :body, label: 'Post Body', input_html: { class: 'tinymce', rows: 10, cols: 120 } %>
        <br />
			  <%= f.button :submit %>
    <% end %>
    <%= tinymce %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="col-sm-8 blog-main">
  <div class="blog-post">
    <h2 class="blog-post-title"><%= @post.title %></h2>
    <p class="blog-post-meta"><%= @post.created_at.to_date.to_formatted_s :long_ordinal %> by Dave Moore
      <% if user_signed_in? %>
         | <%= link_to 'Edit Post', edit_post_path(@post) %>
      <% end %>
    </p>
    <hr>
    <%= raw @post.body %>
    <hr>
    <!-- BEGIN DISQUS EMBED -->
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'superleet'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>
      Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
    </noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

  </div>
</div>
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module sidebat-module-inset">
    <div class="circular"></div>
    <hr>
  </div>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Edit user", edit_user_registration_path(user), :class => 'button-xs') %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>